// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using editaisAPI.Context;

#nullable disable

namespace editaisAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230206170417_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("editaisAPI.Models.Concurso", b =>
                {
                    b.Property<int>("ConcursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Banca")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ConcursoData")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Orgao")
                        .HasColumnType("longtext");

                    b.HasKey("ConcursoId");

                    b.ToTable("Concursos");
                });

            modelBuilder.Entity("editaisAPI.Models.Disciplina", b =>
                {
                    b.Property<string>("DisciplinaNome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("ProvaId")
                        .HasColumnType("int");

                    b.HasKey("DisciplinaNome", "ProvaId");

                    b.HasIndex("ProvaId");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("editaisAPI.Models.Prova", b =>
                {
                    b.Property<int>("ProvaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("ConcursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProvaData")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProvaId");

                    b.HasIndex("ConcursoId");

                    b.ToTable("Provas");
                });

            modelBuilder.Entity("editaisAPI.Models.TopicoFilho", b =>
                {
                    b.Property<string>("TopicoFilhoNome")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("TopicoPaiNome")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("DisciplinaNome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("ProvaId")
                        .HasColumnType("int");

                    b.HasKey("TopicoFilhoNome", "TopicoPaiNome", "DisciplinaNome", "ProvaId");

                    b.HasIndex("TopicoPaiNome", "DisciplinaNome", "ProvaId");

                    b.ToTable("TopicoFilhos");
                });

            modelBuilder.Entity("editaisAPI.Models.TopicoNeto", b =>
                {
                    b.Property<string>("TopicoNetoNome")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("TopicoFilhoNome")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("TopicoPaiNome")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("DisciplinaNome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("ProvaId")
                        .HasColumnType("int");

                    b.HasKey("TopicoNetoNome", "TopicoFilhoNome", "TopicoPaiNome", "DisciplinaNome", "ProvaId");

                    b.HasIndex("TopicoFilhoNome", "TopicoPaiNome", "DisciplinaNome", "ProvaId");

                    b.ToTable("TopicoNetos");
                });

            modelBuilder.Entity("editaisAPI.Models.TopicoPai", b =>
                {
                    b.Property<string>("TopicoPaiNome")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("DisciplinaNome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("ProvaId")
                        .HasColumnType("int");

                    b.Property<string>("DiscipddddddlinaNome")
                        .HasColumnType("varchar(80)");

                    b.HasKey("TopicoPaiNome", "DisciplinaNome", "ProvaId");

                    b.HasIndex("DiscipddddddlinaNome", "ProvaId");

                    b.ToTable("Topicos");
                });

            modelBuilder.Entity("editaisAPI.Models.Disciplina", b =>
                {
                    b.HasOne("editaisAPI.Models.Prova", "Prova")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProvaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prova");
                });

            modelBuilder.Entity("editaisAPI.Models.Prova", b =>
                {
                    b.HasOne("editaisAPI.Models.Concurso", "Concurso")
                        .WithMany("Provas")
                        .HasForeignKey("ConcursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concurso");
                });

            modelBuilder.Entity("editaisAPI.Models.TopicoFilho", b =>
                {
                    b.HasOne("editaisAPI.Models.TopicoPai", "TopicoPai")
                        .WithMany("TopicoFilhos")
                        .HasForeignKey("TopicoPaiNome", "DisciplinaNome", "ProvaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopicoPai");
                });

            modelBuilder.Entity("editaisAPI.Models.TopicoNeto", b =>
                {
                    b.HasOne("editaisAPI.Models.TopicoFilho", "TopicoFilho")
                        .WithMany("TopicoNetos")
                        .HasForeignKey("TopicoFilhoNome", "TopicoPaiNome", "DisciplinaNome", "ProvaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopicoFilho");
                });

            modelBuilder.Entity("editaisAPI.Models.TopicoPai", b =>
                {
                    b.HasOne("editaisAPI.Models.Disciplina", "Disciplina")
                        .WithMany("TopicoPais")
                        .HasForeignKey("DiscipddddddlinaNome", "ProvaId");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("editaisAPI.Models.Concurso", b =>
                {
                    b.Navigation("Provas");
                });

            modelBuilder.Entity("editaisAPI.Models.Disciplina", b =>
                {
                    b.Navigation("TopicoPais");
                });

            modelBuilder.Entity("editaisAPI.Models.Prova", b =>
                {
                    b.Navigation("Disciplinas");
                });

            modelBuilder.Entity("editaisAPI.Models.TopicoFilho", b =>
                {
                    b.Navigation("TopicoNetos");
                });

            modelBuilder.Entity("editaisAPI.Models.TopicoPai", b =>
                {
                    b.Navigation("TopicoFilhos");
                });
#pragma warning restore 612, 618
        }
    }
}
